server:
  port: 8080
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/}

spring:
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
#    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}

  data:
    redis:
      repositories:
        enabled: false

ttl:
  redis:
    processing-timer: 3600
#    processing-timer: 25

microservice:
  ml:
    host: ${MICROSERVICE_ML_HOST:localhost}
#    host: ${MICROSERVICE_ML_HOST:video_processing}
    port: ${MICROSERVICE_ML_PORT:8081}
    rout:
      convert: ${MICROSERVICE_ML_PATH:/process}
  translate:
    url: ${MICROSERVICE_TRANSLATE_URL:https://translate.api.cloud.yandex.net/translate/v2/translate}

yandex:
  translate:
    api-ket: ${YANDEX_TRANSLATE_API_KEY:_}