version: "3"

services:
  video_processing:
    image: trrttrtrsrfewrwed/big_video_processing_bs
    build: video_processing
    ports:
      - "8081:8081"
    env_file: core.env  

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  core:
    image: trrttrtrsrfewrwed/core
    build:
      context: ./core/
      dockerfile: ./Dockerfile-core
    ports:
      - "8080:8080"
    env_file: core.env
    depends_on:
      - redis
