version: "3"

services:
  video_processing:
    build: video_processing
    ports:
      - "8081:8081"

  core:
    build:
      context: ./core/
      dockerfile: ./Dockerfile-core
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"