#!/bin/bash
mkdir checkpoints
chunk1_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/pytorch_model-00001-of-00002.bin"
chunk2_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/pytorch_model-00002-of-00002.bin"
index_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/pytorch_model.bin.index.json"
config_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/config.json"
preprocessor_config_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/preprocessor_config.json"
merges_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/merges.txt"
special_tokens_map_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/special_tokens_map.json"
tokenizer_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/tokenizer.json"
tokenizer_config_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/tokenizer_config.json"
vocab_download_url="https://huggingface.co/Salesforce/blip2-opt-2.7b/resolve/main/vocab.json"
wget ${chunk1_download_url} -O "checkpoints/pytorch_model-00001-of-00002.bin"
wget ${chunk2_download_url} -O "checkpoints/pytorch_model-00002-of-00002.bin"
wget ${index_download_url} -O "checkpoints/pytorch_model.bin.index.json"
wget ${config_download_url} -O "checkpoints/config.json"
wget ${preprocessor_config_download_url} -O "checkpoints/preprocessor_config.json"
wget ${merges_download_url} -O "checkpoints/merges.txt"
wget ${special_tokens_map_download_url} -O "checkpoints/special_tokens_map.json"
wget ${tokenizer_download_url} -O "checkpoints/tokenizer.json"
wget ${tokenizer_config_download_url} -O "checkpoints/tokenizer_config.json"
wget ${vocab_download_url} -O "checkpoints/vocab.json"
